import React, { createContext, useContext, useState, type ReactNode } from 'react'

type Language = 'EN' | 'FR' | 'ES' | 'DE'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  EN: {
    'welcome.title': 'Welcome to Learnify',
    'welcome.subtitle': 'Discover thousands of courses and start your learning journey today',
    'courses.popular': 'Popular Courses',
    'courses.viewAll': 'View All',
    'courses.showLess': 'Show Less',
    'courses.cached': 'Cached',
    'courses.noLessons': 'No lessons available for this course.',
    'courses.featuredLesson': 'Featured Lesson',
    'courses.allLessons': 'All Lessons',
    'courses.aboutCourse': 'About This Course',
    'courses.lessonsCount': 'lessons',
    'courses.difficulty': 'Difficulty',
    'courses.category': 'Category',
    'courses.duration': 'Duration',
    'courses.progress': 'Course Progress',
    'courses.enrolled': 'Enrolled',
    'courses.notEnrolled': 'Not Enrolled',
    'button.getStarted': 'Get Started',
    'button.browseCourses': 'Browse Courses',
    'button.viewCourse': 'View Course',
    'button.enrollNow': 'Enroll Now',
    'button.enrolled': '✓ Enrolled (Click to Unenroll)',
    'button.unenroll': 'Unenroll',
    'button.markComplete': 'Mark as Complete',
    'button.completed': '✓ Completed',
    'button.tryAgain': 'Try Again',
    'button.goHome': 'Go to Home',
    'button.goBack': 'Go Back',
    'button.refresh': 'Refresh Page',
    'button.previous': '← Previous',
    'button.next': 'Next →',
    'button.backToCourse': 'Back to Course',
    'button.viewLesson': 'View Lesson',
    'stats.courses': 'Courses Available',
    'stats.students': 'Active Students',
    'stats.instructors': 'Expert Instructors',
    'loading.courses': 'Loading courses...',
    'loading.course': 'Loading course...',
    'loading.lesson': 'Loading lesson...',
    'loading.courseDetails': 'Loading course details...',
    'error.courseNotFound': 'Course Not Found',
    'error.lessonNotFound': 'Lesson Not Found',
    'error.invalidCourseId': 'Invalid Course ID',
    'error.invalidLessonId': 'Invalid Lesson ID',
    'error.serviceUnavailable': 'Service Unavailable',
    'error.unableToLoad': 'Unable to Load Course Content',
    'error.courseNotFoundDesc': 'The course you\'re looking for doesn\'t exist or is no longer available.',
    'error.lessonNotFoundDesc': 'The lesson you\'re looking for doesn\'t exist or is no longer available.',
    'error.invalidIdDesc': 'The ID must be a valid number.',
    'error.serviceUnavailableDesc': 'We\'re having trouble connecting to our servers. Please check your internet connection and try again.',
    'error.unableToLoadDesc': 'We\'re having trouble loading the course lessons. Please check your connection and try again.',
    'offline.title': 'You\'re offline',
    'offline.description': 'Some features may be limited while offline.',
    'offline.cachedContent': 'Showing cached content - you\'re offline',
    'offline.limitedFeatures': 'Some features may be limited while offline.',
    'progress.completed': 'Completed',
    'progress.incomplete': 'Incomplete',
    'progress.timeSpent': 'Time Spent',
    'progress.completionPercentage': 'Completion Percentage',
    'lesson.difficulty': 'Difficulty',
    'lesson.duration': 'Duration',
    'lesson.order': 'Order',
    'lesson.description': 'Description',
    'lesson.content': 'Content',
    'lesson.resources': 'Additional Resources',
    'lesson.notes': '📄 Lesson Notes (PDF)',
    'lesson.sourceCode': '💻 Source Code',
    'lesson.documentation': '🔗 Official Documentation',
    'lesson.download': 'Download',
    'lesson.view': 'View',
    'lesson.open': 'Open',
    'breadcrumb.home': 'Home',
    'breadcrumb.course': 'Course',
    'breadcrumb.lesson': 'Lesson',
    'footer.builtWith': 'built with ❤️ & ☕ @ispark_classroom',
    'debug.enrolling': 'Enrolling in course...',
    'debug.unenrolling': 'Unenrolling from course...',
    'debug.markingComplete': 'Marking lesson as complete...',
    'debug.markingIncomplete': 'Marking lesson as incomplete...',
    'debug.fetchingCourses': 'Fetching courses from API...',
    'debug.fetchingLessons': 'Fetching lessons for course...',
    'debug.cacheHit': 'Using cached data for course',
    'debug.cacheMiss': 'Cache miss, fetching fresh data for course',
    'debug.apiSuccess': 'API call successful',
    'debug.apiError': 'API call failed',
    'debug.stateUpdate': 'Redux state updated',
    'debug.optimisticUpdate': 'Optimistic update applied',
    'debug.persistData': 'Data persisted to localStorage',
    'debug.rehydrateData': 'Data rehydrated from localStorage',
    'feedback.enrollmentSuccess': 'Successfully enrolled in course!',
    'feedback.unenrollmentSuccess': 'Successfully unenrolled from course!',
    'feedback.lessonComplete': 'Lesson marked as complete!',
    'feedback.lessonIncomplete': 'Lesson marked as incomplete!',
    'feedback.progressSaved': 'Progress saved successfully!',
    'feedback.dataCached': 'Data cached for offline use',
    'feedback.networkError': 'Network error - using cached data',
    'feedback.serverError': 'Server error - please try again',
    'feedback.loadingCourses': 'Loading courses...',
    'feedback.loadingLessons': 'Loading lessons...',
    'feedback.loadingCourse': 'Loading course details...',
    'feedback.loadingLesson': 'Loading lesson content...',
    'mobile.menuOpen': 'Menu opened',
    'mobile.menuClose': 'Menu closed',
    'mobile.scrollToTop': 'Scroll to top',
    'mobile.scrollToBottom': 'Scroll to bottom',
    'mobile.swipeLeft': 'Swipe left for more options',
    'mobile.swipeRight': 'Swipe right to go back',
    'mobile.pullToRefresh': 'Pull to refresh',
    'mobile.tapToExpand': 'Tap to expand',
    'mobile.tapToCollapse': 'Tap to collapse',
    'accessibility.skipToContent': 'Skip to main content',
    'accessibility.closeDialog': 'Close dialog',
    'accessibility.openMenu': 'Open menu',
    'accessibility.nextLesson': 'Go to next lesson',
    'accessibility.previousLesson': 'Go to previous lesson',
    'accessibility.playVideo': 'Play video',
    'accessibility.pauseVideo': 'Pause video',
    'accessibility.muteAudio': 'Mute audio',
    'accessibility.unmuteAudio': 'Unmute audio',
    'accessibility.increaseVolume': 'Increase volume',
    'accessibility.decreaseVolume': 'Decrease volume',
    'accessibility.fullscreen': 'Enter fullscreen',
    'accessibility.exitFullscreen': 'Exit fullscreen',
    'accessibility.zoomIn': 'Zoom in',
    'accessibility.zoomOut': 'Zoom out',
    'accessibility.resetZoom': 'Reset zoom',
    'accessibility.highContrast': 'High contrast mode',
    'accessibility.largeText': 'Large text mode',
    'accessibility.screenReader': 'Screen reader friendly',
    'accessibility.keyboardNavigation': 'Keyboard navigation',
    'accessibility.focusIndicator': 'Focus indicator',
    'accessibility.announcement': 'Announcement',
    'accessibility.statusUpdate': 'Status update',
    'accessibility.progressUpdate': 'Progress update',
    'accessibility.errorAnnouncement': 'Error announcement',
    'accessibility.successAnnouncement': 'Success announcement',
    'accessibility.warningAnnouncement': 'Warning announcement',
    'accessibility.infoAnnouncement': 'Information announcement',
  },
  FR: {
    'welcome.title': 'Bienvenue sur Learnify',
    'welcome.subtitle': 'Découvrez des milliers de cours et commencez votre parcours d\'apprentissage aujourd\'hui',
    'courses.popular': 'Cours Populaires',
    'courses.viewAll': 'Voir Tout',
    'courses.showLess': 'Voir Moins',
    'courses.cached': 'En Cache',
    'courses.noLessons': 'Aucune leçon disponible pour ce cours.',
    'courses.featuredLesson': 'Leçon Vedette',
    'courses.allLessons': 'Toutes les Leçons',
    'courses.aboutCourse': 'À Propos de Ce Cours',
    'courses.lessonsCount': 'leçons',
    'courses.difficulty': 'Difficulté',
    'courses.category': 'Catégorie',
    'courses.duration': 'Durée',
    'courses.progress': 'Progrès du Cours',
    'courses.enrolled': 'Inscrit',
    'courses.notEnrolled': 'Non Inscrit',
    'courses.lessonContentPlaceholder': 'Le contenu de la leçon va ici.',
    'button.getStarted': 'Commencer',
    'button.browseCourses': 'Parcourir les Cours',
    'button.viewCourse': 'Voir le Cours',
    'button.enrollNow': 'S\'inscrire Maintenant',
    'button.enrolled': '✓ Inscrit (Cliquer pour Se Désinscrire)',
    'button.unenroll': 'Se Désinscrire',
    'button.markComplete': 'Marquer comme Terminé',
    'button.completed': '✓ Terminé',
    'button.tryAgain': 'Réessayer',
    'button.goHome': 'Aller à l\'Accueil',
    'button.goBack': 'Retour',
    'button.refresh': 'Actualiser la Page',
    'button.previous': '← Précédent',
    'button.next': 'Suivant →',
    'button.backToCourse': 'Retour au Cours',
    'button.viewLesson': 'Voir la Leçon',
    'stats.courses': 'Cours Disponibles',
    'stats.students': 'Étudiants Actifs',
    'stats.instructors': 'Instructeurs Experts',
    'loading.courses': 'Chargement des cours...',
    'loading.course': 'Chargement du cours...',
    'loading.lesson': 'Chargement de la leçon...',
    'loading.courseDetails': 'Chargement des détails du cours...',
    'loading.lessons': 'Chargement des leçons...',
    'error.courseLoadFailed': 'Impossible de Charger le Contenu du Cours',
    'error.courseLoadMessage': 'Nous avons des difficultés à charger les leçons du cours. Veuillez vérifier votre connexion et réessayer.',
    'error.courseNotFound': 'Cours Non Trouvé',
    'error.lessonNotFound': 'Leçon Non Trouvée',
    'error.invalidCourseId': 'ID de Cours Invalide',
    'error.invalidLessonId': 'ID de Leçon Invalide',
    'error.serviceUnavailable': 'Service Indisponible',
    'error.unableToLoad': 'Impossible de Charger le Contenu du Cours',
    'error.courseNotFoundDesc': 'Le cours que vous recherchez n\'existe pas ou n\'est plus disponible.',
    'error.lessonNotFoundDesc': 'La leçon que vous recherchez n\'existe pas ou n\'est plus disponible.',
    'error.invalidIdDesc': 'L\'ID doit être un nombre valide.',
    'error.serviceUnavailableDesc': 'Nous avons des difficultés à nous connecter à nos serveurs. Veuillez vérifier votre connexion internet et réessayer.',
    'error.unableToLoadDesc': 'Nous avons des difficultés à charger les leçons du cours. Veuillez vérifier votre connexion et réessayer.',
    'offline.title': 'Vous êtes hors ligne',
    'offline.description': 'Certaines fonctionnalités peuvent être limitées hors ligne.',
    'offline.cachedContent': 'Affichage du contenu en cache - vous êtes hors ligne',
    'offline.limitedFeatures': 'Certaines fonctionnalités peuvent être limitées hors ligne.',
    'progress.completed': 'Terminé',
    'progress.incomplete': 'Incomplet',
    'progress.timeSpent': 'Temps Passé',
    'progress.completionPercentage': 'Pourcentage de Réussite',
    'lesson.difficulty': 'Difficulté',
    'lesson.duration': 'Durée',
    'lesson.order': 'Ordre',
    'lesson.description': 'Description',
    'lesson.content': 'Contenu',
    'lesson.resources': 'Ressources Supplémentaires',
    'lesson.notes': '📄 Notes de Leçon (PDF)',
    'lesson.sourceCode': '💻 Code Source',
    'lesson.documentation': '🔗 Documentation Officielle',
    'lesson.download': 'Télécharger',
    'lesson.view': 'Voir',
    'lesson.open': 'Ouvrir',
    'breadcrumb.home': 'Accueil',
    'breadcrumb.course': 'Cours',
    'breadcrumb.lesson': 'Leçon',
    'footer.builtWith': 'construit avec ❤️ & ☕ @ispark_classroom',
    'debug.enrolling': 'Inscription au cours...',
    'debug.unenrolling': 'Désinscription du cours...',
    'debug.markingComplete': 'Marquage de la leçon comme terminée...',
    'debug.markingIncomplete': 'Marquage de la leçon comme incomplète...',
    'debug.fetchingCourses': 'Récupération des cours depuis l\'API...',
    'debug.fetchingLessons': 'Récupération des leçons pour le cours...',
    'debug.cacheHit': 'Utilisation des données en cache pour le cours',
    'debug.cacheMiss': 'Cache manqué, récupération de nouvelles données pour le cours',
    'debug.apiSuccess': 'Appel API réussi',
    'debug.apiError': 'Échec de l\'appel API',
    'debug.stateUpdate': 'État Redux mis à jour',
    'debug.optimisticUpdate': 'Mise à jour optimiste appliquée',
    'debug.persistData': 'Données persistées dans localStorage',
    'debug.rehydrateData': 'Données réhydratées depuis localStorage',
    'feedback.enrollmentSuccess': 'Inscription au cours réussie !',
    'feedback.unenrollmentSuccess': 'Désinscription du cours réussie !',
    'feedback.lessonComplete': 'Leçon marquée comme terminée !',
    'feedback.lessonIncomplete': 'Leçon marquée comme incomplète !',
    'feedback.progressSaved': 'Progrès sauvegardé avec succès !',
    'feedback.dataCached': 'Données mises en cache pour utilisation hors ligne',
    'feedback.networkError': 'Erreur réseau - utilisation des données en cache',
    'feedback.serverError': 'Erreur serveur - veuillez réessayer',
    'feedback.loadingCourses': 'Chargement des cours...',
    'feedback.loadingLessons': 'Chargement des leçons...',
    'feedback.loadingCourse': 'Chargement des détails du cours...',
    'feedback.loadingLesson': 'Chargement du contenu de la leçon...',
    'mobile.menuOpen': 'Menu ouvert',
    'mobile.menuClose': 'Menu fermé',
    'mobile.scrollToTop': 'Faire défiler vers le haut',
    'mobile.scrollToBottom': 'Faire défiler vers le bas',
    'mobile.swipeLeft': 'Glisser vers la gauche pour plus d\'options',
    'mobile.swipeRight': 'Glisser vers la droite pour revenir',
    'mobile.pullToRefresh': 'Tirer pour actualiser',
    'mobile.tapToExpand': 'Appuyer pour développer',
    'mobile.tapToCollapse': 'Appuyer pour réduire',
    'accessibility.skipToContent': 'Passer au contenu principal',
    'accessibility.closeDialog': 'Fermer la boîte de dialogue',
    'accessibility.openMenu': 'Ouvrir le menu',
    'accessibility.nextLesson': 'Aller à la leçon suivante',
    'accessibility.previousLesson': 'Aller à la leçon précédente',
    'accessibility.playVideo': 'Lire la vidéo',
    'accessibility.pauseVideo': 'Mettre en pause la vidéo',
    'accessibility.muteAudio': 'Couper le son',
    'accessibility.unmuteAudio': 'Activer le son',
    'accessibility.increaseVolume': 'Augmenter le volume',
    'accessibility.decreaseVolume': 'Diminuer le volume',
    'accessibility.fullscreen': 'Plein écran',
    'accessibility.exitFullscreen': 'Quitter le plein écran',
    'accessibility.zoomIn': 'Zoom avant',
    'accessibility.zoomOut': 'Zoom arrière',
    'accessibility.resetZoom': 'Réinitialiser le zoom',
    'accessibility.highContrast': 'Mode contraste élevé',
    'accessibility.largeText': 'Mode texte large',
    'accessibility.screenReader': 'Compatible lecteur d\'écran',
    'accessibility.keyboardNavigation': 'Navigation au clavier',
    'accessibility.focusIndicator': 'Indicateur de focus',
    'accessibility.announcement': 'Annonce',
    'accessibility.statusUpdate': 'Mise à jour du statut',
    'accessibility.progressUpdate': 'Mise à jour du progrès',
    'accessibility.errorAnnouncement': 'Annonce d\'erreur',
    'accessibility.successAnnouncement': 'Annonce de succès',
    'accessibility.warningAnnouncement': 'Annonce d\'avertissement',
    'accessibility.infoAnnouncement': 'Annonce d\'information',
  },
  ES: {
    'welcome.title': 'Bienvenido a Learnify',
    'welcome.subtitle': 'Descubre miles de cursos y comienza tu viaje de aprendizaje hoy',
    'courses.popular': 'Cursos Populares',
    'courses.viewAll': 'Ver Todo',
    'courses.showLess': 'Ver Menos',
    'courses.cached': 'En Caché',
    'courses.noLessons': 'No hay lecciones disponibles para este curso.',
    'courses.featuredLesson': 'Lección Destacada',
    'courses.allLessons': 'Todas las Lecciones',
    'courses.aboutCourse': 'Acerca de Este Curso',
    'courses.lessonsCount': 'lecciones',
    'courses.difficulty': 'Dificultad',
    'courses.category': 'Categoría',
    'courses.duration': 'Duración',
    'courses.progress': 'Progreso del Curso',
    'courses.enrolled': 'Inscrito',
    'courses.notEnrolled': 'No Inscrito',
    'courses.lessonContentPlaceholder': 'El contenido de la lección va aquí.',
    'button.getStarted': 'Comenzar',
    'button.browseCourses': 'Explorar Cursos',
    'button.viewCourse': 'Ver Curso',
    'button.enrollNow': 'Inscribirse Ahora',
    'button.enrolled': '✓ Inscrito (Hacer Clic para Desinscribirse)',
    'button.unenroll': 'Desinscribirse',
    'button.markComplete': 'Marcar como Completado',
    'button.completed': '✓ Completado',
    'button.tryAgain': 'Intentar de Nuevo',
    'button.goHome': 'Ir al Inicio',
    'button.goBack': 'Volver',
    'button.refresh': 'Actualizar Página',
    'button.previous': '← Anterior',
    'button.next': 'Siguiente →',
    'button.backToCourse': 'Volver al Curso',
    'button.viewLesson': 'Ver Lección',
    'stats.courses': 'Cursos Disponibles',
    'stats.students': 'Estudiantes Activos',
    'stats.instructors': 'Instructores Expertos',
    'loading.courses': 'Cargando cursos...',
    'loading.course': 'Cargando curso...',
    'loading.lesson': 'Cargando lección...',
    'loading.courseDetails': 'Cargando detalles del curso...',
    'loading.lessons': 'Cargando lecciones...',
    'error.courseLoadFailed': 'No Se Puede Cargar el Contenido del Curso',
    'error.courseLoadMessage': 'Tenemos problemas para cargar las lecciones del curso. Por favor verifique su conexión e intente de nuevo.',
    'error.courseNotFound': 'Curso No Encontrado',
    'error.lessonNotFound': 'Lección No Encontrada',
    'error.invalidCourseId': 'ID de Curso Inválido',
    'error.invalidLessonId': 'ID de Lección Inválido',
    'error.serviceUnavailable': 'Servicio No Disponible',
    'error.unableToLoad': 'No Se Puede Cargar el Contenido del Curso',
    'error.courseNotFoundDesc': 'El curso que buscas no existe o ya no está disponible.',
    'error.lessonNotFoundDesc': 'La lección que buscas no existe o ya no está disponible.',
    'error.invalidIdDesc': 'El ID debe ser un número válido.',
    'error.serviceUnavailableDesc': 'Tenemos problemas para conectarnos a nuestros servidores. Por favor verifica tu conexión a internet e inténtalo de nuevo.',
    'error.unableToLoadDesc': 'Tenemos problemas para cargar las lecciones del curso. Por favor verifica tu conexión e inténtalo de nuevo.',
    'offline.title': 'Estás desconectado',
    'offline.description': 'Algunas funciones pueden estar limitadas sin conexión.',
    'offline.cachedContent': 'Mostrando contenido en caché - estás desconectado',
    'offline.limitedFeatures': 'Algunas funciones pueden estar limitadas sin conexión.',
    'progress.completed': 'Completado',
    'progress.incomplete': 'Incompleto',
    'progress.timeSpent': 'Tiempo Transcurrido',
    'progress.completionPercentage': 'Porcentaje de Finalización',
    'lesson.difficulty': 'Dificultad',
    'lesson.duration': 'Duración',
    'lesson.order': 'Orden',
    'lesson.description': 'Descripción',
    'lesson.content': 'Contenido',
    'lesson.resources': 'Recursos Adicionales',
    'lesson.notes': '📄 Notas de Lección (PDF)',
    'lesson.sourceCode': '💻 Código Fuente',
    'lesson.documentation': '🔗 Documentación Oficial',
    'lesson.download': 'Descargar',
    'lesson.view': 'Ver',
    'lesson.open': 'Abrir',
    'breadcrumb.home': 'Inicio',
    'breadcrumb.course': 'Curso',
    'breadcrumb.lesson': 'Lección',
    'footer.builtWith': 'construido con ❤️ & ☕ @ispark_classroom',
    'debug.enrolling': 'Inscribiéndose en el curso...',
    'debug.unenrolling': 'Desinscribiéndose del curso...',
    'debug.markingComplete': 'Marcando lección como completada...',
    'debug.markingIncomplete': 'Marcando lección como incompleta...',
    'debug.fetchingCourses': 'Obteniendo cursos desde la API...',
    'debug.fetchingLessons': 'Obteniendo lecciones para el curso...',
    'debug.cacheHit': 'Usando datos en caché para el curso',
    'debug.cacheMiss': 'Cache perdido, obteniendo datos frescos para el curso',
    'debug.apiSuccess': 'Llamada API exitosa',
    'debug.apiError': 'Llamada API fallida',
    'debug.stateUpdate': 'Estado Redux actualizado',
    'debug.optimisticUpdate': 'Actualización optimista aplicada',
    'debug.persistData': 'Datos persistidos en localStorage',
    'debug.rehydrateData': 'Datos rehidratados desde localStorage',
    'feedback.enrollmentSuccess': '¡Inscripción en el curso exitosa!',
    'feedback.unenrollmentSuccess': '¡Desinscripción del curso exitosa!',
    'feedback.lessonComplete': '¡Lección marcada como completada!',
    'feedback.lessonIncomplete': '¡Lección marcada como incompleta!',
    'feedback.progressSaved': '¡Progreso guardado exitosamente!',
    'feedback.dataCached': 'Datos en caché para uso sin conexión',
    'feedback.networkError': 'Error de red - usando datos en caché',
    'feedback.serverError': 'Error del servidor - por favor inténtalo de nuevo',
    'feedback.loadingCourses': 'Cargando cursos...',
    'feedback.loadingLessons': 'Cargando lecciones...',
    'feedback.loadingCourse': 'Cargando detalles del curso...',
    'feedback.loadingLesson': 'Cargando contenido de la lección...',
    'mobile.menuOpen': 'Menú abierto',
    'mobile.menuClose': 'Menú cerrado',
    'mobile.scrollToTop': 'Desplazar hacia arriba',
    'mobile.scrollToBottom': 'Desplazar hacia abajo',
    'mobile.swipeLeft': 'Deslizar a la izquierda para más opciones',
    'mobile.swipeRight': 'Deslizar a la derecha para volver',
    'mobile.pullToRefresh': 'Tirar para actualizar',
    'mobile.tapToExpand': 'Tocar para expandir',
    'mobile.tapToCollapse': 'Tocar para colapsar',
    'accessibility.skipToContent': 'Saltar al contenido principal',
    'accessibility.closeDialog': 'Cerrar diálogo',
    'accessibility.openMenu': 'Abrir menú',
    'accessibility.nextLesson': 'Ir a la siguiente lección',
    'accessibility.previousLesson': 'Ir a la lección anterior',
    'accessibility.playVideo': 'Reproducir video',
    'accessibility.pauseVideo': 'Pausar video',
    'accessibility.muteAudio': 'Silenciar audio',
    'accessibility.unmuteAudio': 'Activar audio',
    'accessibility.increaseVolume': 'Aumentar volumen',
    'accessibility.decreaseVolume': 'Disminuir volumen',
    'accessibility.fullscreen': 'Pantalla completa',
    'accessibility.exitFullscreen': 'Salir de pantalla completa',
    'accessibility.zoomIn': 'Acercar',
    'accessibility.zoomOut': 'Alejar',
    'accessibility.resetZoom': 'Restablecer zoom',
    'accessibility.highContrast': 'Modo alto contraste',
    'accessibility.largeText': 'Modo texto grande',
    'accessibility.screenReader': 'Compatible con lector de pantalla',
    'accessibility.keyboardNavigation': 'Navegación por teclado',
    'accessibility.focusIndicator': 'Indicador de enfoque',
    'accessibility.announcement': 'Anuncio',
    'accessibility.statusUpdate': 'Actualización de estado',
    'accessibility.progressUpdate': 'Actualización de progreso',
    'accessibility.errorAnnouncement': 'Anuncio de error',
    'accessibility.successAnnouncement': 'Anuncio de éxito',
    'accessibility.warningAnnouncement': 'Anuncio de advertencia',
    'accessibility.infoAnnouncement': 'Anuncio de información',
  },
  DE: {
    'welcome.title': 'Willkommen bei Learnify',
    'welcome.subtitle': 'Entdecken Sie Tausende von Kursen und beginnen Sie heute Ihre Lernreise',
    'courses.popular': 'Beliebte Kurse',
    'courses.viewAll': 'Alle Anzeigen',
    'courses.showLess': 'Weniger Anzeigen',
    'courses.cached': 'Gecacht',
    'courses.noLessons': 'Keine Lektionen für diesen Kurs verfügbar.',
    'courses.featuredLesson': 'Empfohlene Lektion',
    'courses.allLessons': 'Alle Lektionen',
    'courses.aboutCourse': 'Über Diesen Kurs',
    'courses.lessonsCount': 'Lektionen',
    'courses.difficulty': 'Schwierigkeit',
    'courses.category': 'Kategorie',
    'courses.duration': 'Dauer',
    'courses.progress': 'Kursfortschritt',
    'courses.enrolled': 'Eingeschrieben',
    'courses.notEnrolled': 'Nicht Eingeschrieben',
    'courses.lessonContentPlaceholder': 'Lektionsinhalt kommt hier.',
    'button.getStarted': 'Loslegen',
    'button.browseCourses': 'Kurse Durchsuchen',
    'button.viewCourse': 'Kurs Anzeigen',
    'button.enrollNow': 'Jetzt Einschreiben',
    'button.enrolled': '✓ Eingeschrieben (Klicken zum Abmelden)',
    'button.unenroll': 'Abmelden',
    'button.markComplete': 'Als Abgeschlossen Markieren',
    'button.completed': '✓ Abgeschlossen',
    'button.tryAgain': 'Erneut Versuchen',
    'button.goHome': 'Zur Startseite',
    'button.goBack': 'Zurück',
    'button.refresh': 'Seite Aktualisieren',
    'button.previous': '← Vorherige',
    'button.next': 'Nächste →',
    'button.backToCourse': 'Zurück zum Kurs',
    'button.viewLesson': 'Lektion Anzeigen',
    'stats.courses': 'Verfügbare Kurse',
    'stats.students': 'Aktive Studenten',
    'stats.instructors': 'Experten-Dozenten',
    'loading.courses': 'Kurse werden geladen...',
    'loading.course': 'Kurs wird geladen...',
    'loading.lesson': 'Lektion wird geladen...',
    'loading.courseDetails': 'Kursdetails werden geladen...',
    'loading.lessons': 'Lektionen werden geladen...',
    'error.courseLoadFailed': 'Kursinhalt Kann Nicht Geladen Werden',
    'error.courseLoadMessage': 'Wir haben Probleme beim Laden der Kurslektionen. Bitte überprüfen Sie Ihre Verbindung und versuchen Sie es erneut.',
    'error.courseNotFound': 'Kurs Nicht Gefunden',
    'error.lessonNotFound': 'Lektion Nicht Gefunden',
    'error.invalidCourseId': 'Ungültige Kurs-ID',
    'error.invalidLessonId': 'Ungültige Lektion-ID',
    'error.serviceUnavailable': 'Service Nicht Verfügbar',
    'error.unableToLoad': 'Kursinhalt Kann Nicht Geladen Werden',
    'error.courseNotFoundDesc': 'Der gesuchte Kurs existiert nicht oder ist nicht mehr verfügbar.',
    'error.lessonNotFoundDesc': 'Die gesuchte Lektion existiert nicht oder ist nicht mehr verfügbar.',
    'error.invalidIdDesc': 'Die ID muss eine gültige Zahl sein.',
    'error.serviceUnavailableDesc': 'Wir haben Probleme, uns mit unseren Servern zu verbinden. Bitte überprüfen Sie Ihre Internetverbindung und versuchen Sie es erneut.',
    'error.unableToLoadDesc': 'Wir haben Probleme beim Laden der Kurslektionen. Bitte überprüfen Sie Ihre Verbindung und versuchen Sie es erneut.',
    'offline.title': 'Sie sind offline',
    'offline.description': 'Einige Funktionen können offline eingeschränkt sein.',
    'offline.cachedContent': 'Gecachter Inhalt wird angezeigt - Sie sind offline',
    'offline.limitedFeatures': 'Einige Funktionen können offline eingeschränkt sein.',
    'progress.completed': 'Abgeschlossen',
    'progress.incomplete': 'Unvollständig',
    'progress.timeSpent': 'Verbrachte Zeit',
    'progress.completionPercentage': 'Abschlussprozentsatz',
    'lesson.difficulty': 'Schwierigkeit',
    'lesson.duration': 'Dauer',
    'lesson.order': 'Reihenfolge',
    'lesson.description': 'Beschreibung',
    'lesson.content': 'Inhalt',
    'lesson.resources': 'Zusätzliche Ressourcen',
    'lesson.notes': '📄 Lektionsnotizen (PDF)',
    'lesson.sourceCode': '💻 Quellcode',
    'lesson.documentation': '🔗 Offizielle Dokumentation',
    'lesson.download': 'Herunterladen',
    'lesson.view': 'Anzeigen',
    'lesson.open': 'Öffnen',
    'breadcrumb.home': 'Startseite',
    'breadcrumb.course': 'Kurs',
    'breadcrumb.lesson': 'Lektion',
    'footer.builtWith': 'gebaut mit ❤️ & ☕ @ispark_classroom',
    'debug.enrolling': 'Einschreibung in den Kurs...',
    'debug.unenrolling': 'Abmeldung vom Kurs...',
    'debug.markingComplete': 'Lektion als abgeschlossen markieren...',
    'debug.markingIncomplete': 'Lektion als unvollständig markieren...',
    'debug.fetchingCourses': 'Kurse von der API abrufen...',
    'debug.fetchingLessons': 'Lektionen für den Kurs abrufen...',
    'debug.cacheHit': 'Verwende gecachte Daten für den Kurs',
    'debug.cacheMiss': 'Cache-Fehler, frische Daten für den Kurs abrufen',
    'debug.apiSuccess': 'API-Aufruf erfolgreich',
    'debug.apiError': 'API-Aufruf fehlgeschlagen',
    'debug.stateUpdate': 'Redux-Status aktualisiert',
    'debug.optimisticUpdate': 'Optimistische Aktualisierung angewendet',
    'debug.persistData': 'Daten in localStorage persistiert',
    'debug.rehydrateData': 'Daten aus localStorage rehydriert',
    'feedback.enrollmentSuccess': 'Erfolgreich in den Kurs eingeschrieben!',
    'feedback.unenrollmentSuccess': 'Erfolgreich vom Kurs abgemeldet!',
    'feedback.lessonComplete': 'Lektion als abgeschlossen markiert!',
    'feedback.lessonIncomplete': 'Lektion als unvollständig markiert!',
    'feedback.progressSaved': 'Fortschritt erfolgreich gespeichert!',
    'feedback.dataCached': 'Daten für Offline-Nutzung gecacht',
    'feedback.networkError': 'Netzwerkfehler - verwende gecachte Daten',
    'feedback.serverError': 'Serverfehler - bitte versuchen Sie es erneut',
    'feedback.loadingCourses': 'Kurse werden geladen...',
    'feedback.loadingLessons': 'Lektionen werden geladen...',
    'feedback.loadingCourse': 'Kursdetails werden geladen...',
    'feedback.loadingLesson': 'Lektionsinhalt wird geladen...',
    'mobile.menuOpen': 'Menü geöffnet',
    'mobile.menuClose': 'Menü geschlossen',
    'mobile.scrollToTop': 'Nach oben scrollen',
    'mobile.scrollToBottom': 'Nach unten scrollen',
    'mobile.swipeLeft': 'Nach links wischen für mehr Optionen',
    'mobile.swipeRight': 'Nach rechts wischen zum Zurückgehen',
    'mobile.pullToRefresh': 'Ziehen zum Aktualisieren',
    'mobile.tapToExpand': 'Tippen zum Erweitern',
    'mobile.tapToCollapse': 'Tippen zum Zusammenklappen',
    'accessibility.skipToContent': 'Zum Hauptinhalt springen',
    'accessibility.closeDialog': 'Dialog schließen',
    'accessibility.openMenu': 'Menü öffnen',
    'accessibility.nextLesson': 'Zur nächsten Lektion gehen',
    'accessibility.previousLesson': 'Zur vorherigen Lektion gehen',
    'accessibility.playVideo': 'Video abspielen',
    'accessibility.pauseVideo': 'Video pausieren',
    'accessibility.muteAudio': 'Audio stumm schalten',
    'accessibility.unmuteAudio': 'Audio aktivieren',
    'accessibility.increaseVolume': 'Lautstärke erhöhen',
    'accessibility.decreaseVolume': 'Lautstärke verringern',
    'accessibility.fullscreen': 'Vollbild',
    'accessibility.exitFullscreen': 'Vollbild verlassen',
    'accessibility.zoomIn': 'Hineinzoomen',
    'accessibility.zoomOut': 'Herauszoomen',
    'accessibility.resetZoom': 'Zoom zurücksetzen',
    'accessibility.highContrast': 'Hoher Kontrast Modus',
    'accessibility.largeText': 'Großer Text Modus',
    'accessibility.screenReader': 'Bildschirmleser-kompatibel',
    'accessibility.keyboardNavigation': 'Tastaturnavigation',
    'accessibility.focusIndicator': 'Fokus-Indikator',
    'accessibility.announcement': 'Ankündigung',
    'accessibility.statusUpdate': 'Status-Update',
    'accessibility.progressUpdate': 'Fortschritts-Update',
    'accessibility.errorAnnouncement': 'Fehler-Ankündigung',
    'accessibility.successAnnouncement': 'Erfolgs-Ankündigung',
    'accessibility.warningAnnouncement': 'Warnungs-Ankündigung',
    'accessibility.infoAnnouncement': 'Informations-Ankündigung',
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('EN')

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
